language: ruby
rvm:
  - 2.2.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql
  - sudo apt-get install -qq postgresql-server-dev-9.5
  - sudo apt-get install -qq libpq-dev
before_script:
  - psql -c 'create database slowfood_v1_test;' -U postgres
script: bundle exec rspec
